// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Map from "./islands/Map.tsx";
import * as $MenuInstitutionalMobile from "./islands/MenuInstitutionalMobile.tsx";
import * as $MiniMeDoll_MiniMeDoll from "./islands/MiniMeDoll/MiniMeDoll.tsx";
import * as $MiniMeDoll_PopupMiniMe from "./islands/MiniMeDoll/PopupMiniMe.tsx";
import * as $MinicartFooter from "./islands/MinicartFooter.tsx";
import * as $MultiRangeSlider from "./islands/MultiRangeSlider.tsx";
import * as $Notify from "./islands/Notify.tsx";
import * as $PopupDeEntrada from "./islands/PopupDeEntrada.tsx";
import * as $PopupLGPD from "./islands/PopupLGPD.tsx";
import * as $ProductBuyTogether from "./islands/ProductBuyTogether.tsx";
import * as $ProductTextInfoDiscloujure from "./islands/ProductTextInfoDiscloujure.tsx";
import * as $ScrollButton from "./islands/ScrollButton.tsx";
import * as $Selector from "./islands/Selector.tsx";
import * as $ShowPriceItem from "./islands/ShowPriceItem.tsx";
import * as $StarSelector from "./islands/StarSelector.tsx";
import * as $components_DollButtons from "./islands/components/DollButtons.tsx";
import * as $components_DollImage from "./islands/components/DollImage.tsx";
import * as $components_DollParts from "./islands/components/DollParts.tsx";
import * as $components_DollProgress from "./islands/components/DollProgress.tsx";
import * as $components_DollTitle from "./islands/components/DollTitle.tsx";
import * as $formsNossasLojas from "./islands/formsNossasLojas.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Map.tsx": $Map,
    "./islands/MenuInstitutionalMobile.tsx": $MenuInstitutionalMobile,
    "./islands/MiniMeDoll/MiniMeDoll.tsx": $MiniMeDoll_MiniMeDoll,
    "./islands/MiniMeDoll/PopupMiniMe.tsx": $MiniMeDoll_PopupMiniMe,
    "./islands/MinicartFooter.tsx": $MinicartFooter,
    "./islands/MultiRangeSlider.tsx": $MultiRangeSlider,
    "./islands/Notify.tsx": $Notify,
    "./islands/PopupDeEntrada.tsx": $PopupDeEntrada,
    "./islands/PopupLGPD.tsx": $PopupLGPD,
    "./islands/ProductBuyTogether.tsx": $ProductBuyTogether,
    "./islands/ProductTextInfoDiscloujure.tsx": $ProductTextInfoDiscloujure,
    "./islands/ScrollButton.tsx": $ScrollButton,
    "./islands/Selector.tsx": $Selector,
    "./islands/ShowPriceItem.tsx": $ShowPriceItem,
    "./islands/StarSelector.tsx": $StarSelector,
    "./islands/components/DollButtons.tsx": $components_DollButtons,
    "./islands/components/DollImage.tsx": $components_DollImage,
    "./islands/components/DollParts.tsx": $components_DollParts,
    "./islands/components/DollProgress.tsx": $components_DollProgress,
    "./islands/components/DollTitle.tsx": $components_DollTitle,
    "./islands/formsNossasLojas.tsx": $formsNossasLojas,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
