// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $MenuInstitutionalMobile from "./islands/MenuInstitutionalMobile.tsx";
import * as $MinicartFooter from "./islands/MinicartFooter.tsx";
import * as $MultiRangeSlider from "./islands/MultiRangeSlider.tsx";
import * as $Notify from "./islands/Notify.tsx";
import * as $ProductBuyTogether from "./islands/ProductBuyTogether.tsx";
import * as $ProductTextInfoDiscloujure from "./islands/ProductTextInfoDiscloujure.tsx";
import * as $ScrollButton from "./islands/ScrollButton.tsx";
import * as $Selector from "./islands/Selector.tsx";
import * as $ShowPriceItem from "./islands/ShowPriceItem.tsx";
import * as $StarSelector from "./islands/StarSelector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/MenuInstitutionalMobile.tsx": $MenuInstitutionalMobile,
    "./islands/MinicartFooter.tsx": $MinicartFooter,
    "./islands/MultiRangeSlider.tsx": $MultiRangeSlider,
    "./islands/Notify.tsx": $Notify,
    "./islands/ProductBuyTogether.tsx": $ProductBuyTogether,
    "./islands/ProductTextInfoDiscloujure.tsx": $ProductTextInfoDiscloujure,
    "./islands/ScrollButton.tsx": $ScrollButton,
    "./islands/Selector.tsx": $Selector,
    "./islands/ShowPriceItem.tsx": $ShowPriceItem,
    "./islands/StarSelector.tsx": $StarSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
