// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import type { Manifest } from "$fresh/server.ts";
import * as $MinicartFooter from "./islands/MinicartFooter.tsx";
import * as $MultiRangeSlider from "./islands/MultiRangeSlider.tsx";
import * as $Notify from "./islands/Notify.tsx";
import * as $ShowPriceItem from "./islands/ShowPriceItem.tsx";
import * as $_app from "./routes/_app.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/MinicartFooter.tsx": $MinicartFooter,
    "./islands/MultiRangeSlider.tsx": $MultiRangeSlider,
    "./islands/Notify.tsx": $Notify,
    "./islands/ShowPriceItem.tsx": $ShowPriceItem,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
