// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$4 from "./loaders/availableIcons.ts";
import * as $$$0 from "./loaders/BuyTogether/constants.ts";
import * as $$$1 from "./loaders/BuyTogether/getInitialProducts.ts";
import * as $$$2 from "./loaders/BuyTogether/getNewProduct.ts";
import * as $$$3 from "./loaders/BuyTogether/types.ts";
import * as $$$5 from "./loaders/geolocation.ts";
import * as $$$6 from "./loaders/icons.ts";
import * as $$$7 from "./loaders/minicart.ts";
import * as $$$8 from "./loaders/product/backgroundBanner.ts";
import * as $$$9 from "./loaders/product/rotativeText.ts";
import * as $$$10 from "./loaders/savedColors.ts";
import * as $$$11 from "./loaders/searchDocuments.ts";
import * as $$$12 from "./loaders/sizebay.ts";
import * as $$$13 from "./loaders/user.ts";
import * as $$$14 from "./loaders/vtexReviewsAndRatings/constants.ts";
import * as $$$15 from "./loaders/vtexReviewsAndRatings/index.ts";
import * as $$$16 from "./loaders/vtexReviewsAndRatings/queries.ts";
import * as $$$17 from "./loaders/vtexReviewsAndRatings/types.ts";
import * as $$$18 from "./loaders/wishlist.ts";
import * as $$$19 from "./loaders/youtubeVideo.ts";
import * as $$$$$$0 from "./sections/AboutUs/AboutUsBanner.tsx";
import * as $$$$$$1 from "./sections/AboutUs/AboutUsBubbles.tsx";
import * as $$$$$$2 from "./sections/AboutUs/AboutUsCompanyInfo.tsx";
import * as $$$$$$3 from "./sections/AboutUs/AboutUsIntroduction.tsx";
import * as $$$$$$4 from "./sections/AboutUs/AboutUsVideo.tsx";
import * as $$$$$$5 from "./sections/Animation/Animation.tsx";
import * as $$$$$$6 from "./sections/BenefitsBar/BenefitsBar.tsx";
import * as $$$$$$7 from "./sections/BreadcrumbInstitucional/Breadcrumb.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryBottomBanner.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$10 from "./sections/CollectionBanner/CollectionBanner.tsx";
import * as $$$$$$11 from "./sections/Component.tsx";
import * as $$$$$$12 from "./sections/Content/FAQ.tsx";
import * as $$$$$$13 from "./sections/Content/Hero.tsx";
import * as $$$$$$14 from "./sections/Content/Intro.tsx";
import * as $$$$$$15 from "./sections/Content/Logos.tsx";
import * as $$$$$$16 from "./sections/Content/RotativeText.tsx";
import * as $$$$$$17 from "./sections/DuvidasFrequentes/DuvidasFrequentes.tsx";
import * as $$$$$$18 from "./sections/Footer/Footer.tsx";
import * as $$$$$$19 from "./sections/GiftShelf/GiftShelf.tsx";
import * as $$$$$$20 from "./sections/Header/Header.tsx";
import * as $$$$$$21 from "./sections/HomeToCategoryBanner/HomeToCategoryBanner.tsx";
import * as $$$$$$22 from "./sections/Images/BackgroundBanner.tsx";
import * as $$$$$$23 from "./sections/Images/Banner.tsx";
import * as $$$$$$24 from "./sections/Images/Carousel.tsx";
import * as $$$$$$25 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$26 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$27 from "./sections/InteractiveBanner/InteractiveBanner.tsx";
import * as $$$$$$28 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$29 from "./sections/MenuInstitucional/MenuInstitucional.tsx";
import * as $$$$$$30 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$31 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$32 from "./sections/Miscellaneous/Spacer.tsx";
import * as $$$$$$33 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$34 from "./sections/NossasLojas/NossasLojas.tsx";
import * as $$$$$$35 from "./sections/NossasLojas/query.ts";
import * as $$$$$$36 from "./sections/NossasLojas/types.ts";
import * as $$$$$$37 from "./sections/Policy/Policy.tsx";
import * as $$$$$$38 from "./sections/PopupLGPD/PopupLGPD.tsx";
import * as $$$$$$39 from "./sections/Product/ProductBuyTogether.tsx";
import * as $$$$$$40 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$41 from "./sections/Product/ProductReviews.tsx";
import * as $$$$$$42 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$43 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$44 from "./sections/Product/QuickView.tsx";
import * as $$$$$$45 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$46 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$47 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$48 from "./sections/Session.tsx";
import * as $$$$$$49 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$50 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$51 from "./sections/TabLayout/TabLayout.tsx";
import * as $$$$$$52 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$4,
    "site/loaders/BuyTogether/constants.ts": $$$0,
    "site/loaders/BuyTogether/getInitialProducts.ts": $$$1,
    "site/loaders/BuyTogether/getNewProduct.ts": $$$2,
    "site/loaders/BuyTogether/types.ts": $$$3,
    "site/loaders/geolocation.ts": $$$5,
    "site/loaders/icons.ts": $$$6,
    "site/loaders/minicart.ts": $$$7,
    "site/loaders/product/backgroundBanner.ts": $$$8,
    "site/loaders/product/rotativeText.ts": $$$9,
    "site/loaders/savedColors.ts": $$$10,
    "site/loaders/searchDocuments.ts": $$$11,
    "site/loaders/sizebay.ts": $$$12,
    "site/loaders/user.ts": $$$13,
    "site/loaders/vtexReviewsAndRatings/constants.ts": $$$14,
    "site/loaders/vtexReviewsAndRatings/index.ts": $$$15,
    "site/loaders/vtexReviewsAndRatings/queries.ts": $$$16,
    "site/loaders/vtexReviewsAndRatings/types.ts": $$$17,
    "site/loaders/wishlist.ts": $$$18,
    "site/loaders/youtubeVideo.ts": $$$19,
  },
  "sections": {
    "site/sections/AboutUs/AboutUsBanner.tsx": $$$$$$0,
    "site/sections/AboutUs/AboutUsBubbles.tsx": $$$$$$1,
    "site/sections/AboutUs/AboutUsCompanyInfo.tsx": $$$$$$2,
    "site/sections/AboutUs/AboutUsIntroduction.tsx": $$$$$$3,
    "site/sections/AboutUs/AboutUsVideo.tsx": $$$$$$4,
    "site/sections/Animation/Animation.tsx": $$$$$$5,
    "site/sections/BenefitsBar/BenefitsBar.tsx": $$$$$$6,
    "site/sections/BreadcrumbInstitucional/Breadcrumb.tsx": $$$$$$7,
    "site/sections/Category/CategoryBottomBanner.tsx": $$$$$$8,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$9,
    "site/sections/CollectionBanner/CollectionBanner.tsx": $$$$$$10,
    "site/sections/Component.tsx": $$$$$$11,
    "site/sections/Content/FAQ.tsx": $$$$$$12,
    "site/sections/Content/Hero.tsx": $$$$$$13,
    "site/sections/Content/Intro.tsx": $$$$$$14,
    "site/sections/Content/Logos.tsx": $$$$$$15,
    "site/sections/Content/RotativeText.tsx": $$$$$$16,
    "site/sections/DuvidasFrequentes/DuvidasFrequentes.tsx": $$$$$$17,
    "site/sections/Footer/Footer.tsx": $$$$$$18,
    "site/sections/GiftShelf/GiftShelf.tsx": $$$$$$19,
    "site/sections/Header/Header.tsx": $$$$$$20,
    "site/sections/HomeToCategoryBanner/HomeToCategoryBanner.tsx": $$$$$$21,
    "site/sections/Images/BackgroundBanner.tsx": $$$$$$22,
    "site/sections/Images/Banner.tsx": $$$$$$23,
    "site/sections/Images/Carousel.tsx": $$$$$$24,
    "site/sections/Images/ImageGallery.tsx": $$$$$$25,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$26,
    "site/sections/InteractiveBanner/InteractiveBanner.tsx": $$$$$$27,
    "site/sections/Links/LinkTree.tsx": $$$$$$28,
    "site/sections/MenuInstitucional/MenuInstitucional.tsx": $$$$$$29,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$30,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$31,
    "site/sections/Miscellaneous/Spacer.tsx": $$$$$$32,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$33,
    "site/sections/NossasLojas/NossasLojas.tsx": $$$$$$34,
    "site/sections/NossasLojas/query.ts": $$$$$$35,
    "site/sections/NossasLojas/types.ts": $$$$$$36,
    "site/sections/Policy/Policy.tsx": $$$$$$37,
    "site/sections/PopupLGPD/PopupLGPD.tsx": $$$$$$38,
    "site/sections/Product/ProductBuyTogether.tsx": $$$$$$39,
    "site/sections/Product/ProductDetails.tsx": $$$$$$40,
    "site/sections/Product/ProductReviews.tsx": $$$$$$41,
    "site/sections/Product/ProductShelf.tsx": $$$$$$42,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$43,
    "site/sections/Product/QuickView.tsx": $$$$$$44,
    "site/sections/Product/SearchResult.tsx": $$$$$$45,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$46,
    "site/sections/Product/Wishlist.tsx": $$$$$$47,
    "site/sections/Session.tsx": $$$$$$48,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$49,
    "site/sections/Social/WhatsApp.tsx": $$$$$$50,
    "site/sections/TabLayout/TabLayout.tsx": $$$$$$51,
    "site/sections/Theme/Theme.tsx": $$$$$$52,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/wishlist/submit.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
